import requests
import threading
import time
from queue import Queue
from rich.console import Console
from rich.panel import Panel
import os

# --- Configuration ---
SOURCES = [
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
    "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/http/data.txt",
    "https://raw.githubusercontent.com/Thordata/awesome-free-proxy-list/main/proxies/http.txt",
    "https://raw.githubusercontent.com/Munachukwuw/Best-Free-Proxies/main/http.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
    "https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http",
    "https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/http.txt"
]

OUTPUT_FILE = "proxies.txt"
THREADS = 75
TIMEOUT = 5
TEST_URL = "http://httpbin.org/ip"

console = Console()
file_lock = threading.Lock()
stats = {"found": 0, "scanned": 0, "failed": 0}
stats_lock = threading.Lock()

def test_worker(q):
    while not q.empty():
        try:
            proxy = q.get_nowait()
        except:
            break
            
        try:
            # Test proxy
            proxies = {
                "http": f"http://{proxy}", 
                "https": f"http://{proxy}"
            }
            
            start_time = time.time()
            r = requests.get(
                TEST_URL, 
                proxies=proxies, 
                timeout=TIMEOUT,
                headers={'User-Agent': 'Mozilla/5.0'}  # Add user agent
            )
            latency = round((time.time() - start_time) * 1000)
            
            if r.status_code == 200:
                # Debug output
                console.print(f"[bold green][ALIVE][/bold green] {proxy:<22} | [cyan]{latency}ms[/cyan]")
                
                # Write to file with immediate flush
                with file_lock:
                    try:
                        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
                            f.write(f"{proxy}\n")
                            f.flush()  # Force write to disk
                            os.fsync(f.fileno())  # Ensure it's written to disk
                    except Exception as e:
                        console.print(f"[red]Error writing to file: {e}[/red]")
                
                with stats_lock:
                    stats["found"] += 1
            else:
                with stats_lock:
                    stats["failed"] += 1
                    
        except requests.exceptions.Timeout:
            with stats_lock:
                stats["failed"] += 1
        except requests.exceptions.ConnectionError:
            with stats_lock:
                stats["failed"] += 1
        except Exception as e:
            with stats_lock:
                stats["failed"] += 1
        finally:
            with stats_lock:
                stats["scanned"] += 1
            q.task_done()

def verify_file_writing():
    """Test if file writing works"""
    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("# Proxy List - Generated by scraper\n")
            f.flush()
        console.print("[green]✓ File write test successful[/green]")
        return True
    except Exception as e:
        console.print(f"[red]✗ File write test failed: {e}[/red]")
        return False

def main():
    # Clear and test file
    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("# Working HTTP/HTTPS Proxies\n")
            f.write("# Generated: " + time.strftime("%Y-%m-%d %H:%M:%S") + "\n\n")
        console.print(f"[green]✓ Created output file: {OUTPUT_FILE}[/green]")
    except Exception as e:
        console.print(f"[red]Failed to create output file: {e}[/red]")
        return

    console.print(Panel("[bold cyan]HTTPS Proxy Scraper[/bold cyan]", expand=False))
    console.print(f"[*] Timeout: [bold yellow]{TIMEOUT}s[/bold yellow] | Threads: [bold yellow]{THREADS}[/bold yellow]")
    
    # 1. Scraping Sources
    raw_list = set()
    source_counts = {}
    
    with console.status("[bold white]Fetching proxy lists..."):
        for i, url in enumerate(SOURCES, 1):
            try:
                source_name = url.split('/')[-1].split('?')[0][:20]
                console.print(f"  Fetching {i}/{len(SOURCES)}: {source_name}...")
                
                res = requests.get(url, timeout=10)
                extracted = [p.strip() for p in res.text.splitlines() if ":" in p and p.strip()]
                raw_list.update(extracted)
                source_counts[source_name] = len(extracted)
                
                console.print(f"    → Found {len(extracted)} proxies")
            except Exception as e:
                console.print(f"    [red]→ Failed: {str(e)[:50]}[/red]")
                continue

    if not raw_list:
        console.print("[red]No proxies found from any source![/red]")
        return

    # 2. Validate proxies format
    valid_proxies = []
    invalid_count = 0
    
    for p in raw_list:
        try:
            ip, port = p.split(":")
            # Basic validation
            if len(ip.split('.')) == 4 and port.isdigit():
                valid_proxies.append(p)
            else:
                invalid_count += 1
        except:
            invalid_count += 1

    # 3. Setup Queue
    proxy_queue = Queue()
    for p in valid_proxies:
        proxy_queue.put(p)

    console.print(f"\n[*] Proxy summary:")
    console.print(f"  • Total fetched: [bold cyan]{len(raw_list)}[/bold cyan]")
    console.print(f"  • Valid format: [bold green]{len(valid_proxies)}[/bold green]")
    console.print(f"  • Invalid format: [bold yellow]{invalid_count}[/bold yellow]")
    console.print(f"\n[*] Starting testing with {THREADS} threads...\n")

    # 4. Execution
    start_run = time.time()
    threads = []
    for _ in range(min(THREADS, len(valid_proxies))):
        t = threading.Thread(target=test_worker, args=(proxy_queue,), daemon=True)
        t.start()
        threads.append(t)
    
    # Wait for completion with progress updates
    while any(t.is_alive() for t in threads):
        time.sleep(1)
        with stats_lock:
            scanned = stats["scanned"]
            found = stats["found"]
            console.print(f"  Progress: {scanned}/{len(valid_proxies)} | Found: {found}", end='\r')
    
    # Block until finished
    proxy_queue.join()
    
    duration = round(time.time() - start_run, 2)
    
    # Final summary
    console.print("\n" + "━" * 50)
    console.print("[bold green]✓ SCANNING COMPLETE[/bold green]")
    console.print(f"• Total scanned: [bold white]{stats['scanned']}[/bold white]")
    console.print(f"• Working proxies: [bold green]{stats['found']}[/bold green]")
    console.print(f"• Failed: [bold red]{stats['failed']}[/bold red]")
    console.print(f"• Time taken: {duration}s")
    
    # Verify file contents
    try:
        with open(OUTPUT_FILE, 'r') as f:
            lines = [l.strip() for l in f.readlines() if l.strip() and not l.startswith('#')]
            console.print(f"• Proxies in file: [bold cyan]{len(lines)}[/bold cyan]")
            
        if len(lines) != stats['found']:
            console.print("[yellow]⚠ Warning: File count doesn't match found proxies![/yellow]")
        elif len(lines) > 0:
            console.print(f"[green]✓ Successfully saved {len(lines)} proxies to {OUTPUT_FILE}[/green]")
            console.print(f"  First few proxies: {', '.join(lines[:3])}")
        else:
            console.print("[red]✗ No proxies were saved to the file![/red]")
    except Exception as e:
        console.print(f"[red]Error reading output file: {e}[/red]")
    
    console.print("━" * 50)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[red]Session Aborted.[/red]")
    except Exception as e:
        console.print(f"\n[red]Unexpected error: {e}[/red]")
